sudo: false
language: php
addons:
  hosts:
    - condom-shop.test
    - static.condom-shop.test
    - new-condom-shop.test
    - static.new-condom-shop.test
  apt:
    packages:
      - nginx
      - realpath

php:
  - 5.4

# cache dirs
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.selenium

before_install:
  # xvfb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"

install:
  - export YII_ENV=test
  - export DISPLAY=:99
  # nginx + php-fpm
  - config/travis/web-server.sh
  # selenuim
  - config/travis/selenium.sh
  # composer
  - travis_retry composer self-update 1.0.0-beta1 && composer --version
  - travis_retry composer global require fxp/composer-asset-plugin:dev-master --no-plugins
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update 1.0.0-beta2
  - composer config --global github-oauth.github.com 8e715ae4bc8a6fe4737f726897dbdef0868e2b90
  - travis_retry composer install --prefer-dist --no-interaction
  - composer show --self && composer global show -i && composer show -i
  - sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php

before_script:
  - ps axu
  - cd $TRAVIS_BUILD_DIR/tests
  - $TRAVIS_BUILD_DIR/vendor/bin/codecept build
  - cat /etc/hosts
  - curl -XGET 'http://condom-shop.test'

script:
  - cd $TRAVIS_BUILD_DIR/tests
  - $TRAVIS_BUILD_DIR/vendor/bin/codecept run -vvv
